// <auto-generated />
using System;
using KiwiTaskAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiwiTaskAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419093543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KiwiTaskAPI.Models.Attachment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<Guid?>("Tasksid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ctx_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("uploader_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Tasksid");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskCategory", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("task_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("taskid")
                        .HasColumnType("char(36)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("taskid");

                    b.ToTable("task_categories");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Tasks", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("budget")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("budget_amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("city")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("estimated_hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("postcode")
                        .HasColumnType("longtext");

                    b.Property<Guid>("poster_id")
                        .HasColumnType("char(36)");

                    b.Property<int>("pricing_type")
                        .HasColumnType("int");

                    b.Property<string>("suburb")
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Attachment", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Tasks", null)
                        .WithMany("attachments")
                        .HasForeignKey("Tasksid");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskCategory", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Tasks", "task")
                        .WithMany("TaskCategories")
                        .HasForeignKey("taskid");

                    b.Navigation("task");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Tasks", b =>
                {
                    b.Navigation("TaskCategories");

                    b.Navigation("attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
