// <auto-generated />
using System;
using KiwiTaskAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiwiTaskAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621043500_createTaskCommentsModel")]
    partial class createTaskCommentsModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KiwiTaskAPI.Models.NotificationSettings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("app_enabled")
                        .HasColumnType("int");

                    b.Property<int>("email_enabled")
                        .HasColumnType("int");

                    b.Property<int>("marketing_opt")
                        .HasColumnType("int");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("notification_settings");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.PreferredCategories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("preferred_categories");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskAttachment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<Guid?>("Tasksid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ctx_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("uploader_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Tasksid");

                    b.ToTable("task_attachments");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskCategory", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("task_categories");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskCates", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("task_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("task_id");

                    b.ToTable("task_cates");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskComments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("attachments")
                        .HasColumnType("longtext");

                    b.Property<int?>("comment_id")
                        .HasColumnType("int");

                    b.Property<Guid>("commenter_user_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("task_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("commenter_user_id");

                    b.HasIndex("task_id");

                    b.ToTable("task_comments");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskMatches", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("confirm_expires")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("confirmed")
                        .HasColumnType("int");

                    b.Property<DateTime>("matched_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("task_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("tasker_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("task_matches");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskNotifications", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("is_read")
                        .HasColumnType("int");

                    b.Property<int?>("offer_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("read_at")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("task_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("task_notifications");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskOffers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("attachments")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("expired_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("message")
                        .HasColumnType("text");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("task_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("task_id");

                    b.HasIndex("user_id");

                    b.ToTable("task_offers");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Tasks", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("budget")
                        .HasColumnType("longtext");

                    b.Property<string>("city")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("estimated_hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("location")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("postcode")
                        .HasColumnType("longtext");

                    b.Property<Guid>("poster_id")
                        .HasColumnType("char(36)");

                    b.Property<int>("pricing_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("schedule_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("suburb")
                        .HasColumnType("longtext");

                    b.Property<int>("task_type")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("poster_id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.UserPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("user_password");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Users", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("avatar_url")
                        .HasColumnType("longtext");

                    b.Property<string>("bio")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("educations")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("experiences")
                        .HasColumnType("longtext");

                    b.Property<string>("firstname")
                        .HasColumnType("longtext");

                    b.Property<string>("introduction")
                        .HasColumnType("longtext");

                    b.Property<bool?>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("is_recommand_required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lastname")
                        .HasColumnType("longtext");

                    b.Property<string>("phone_number")
                        .HasColumnType("longtext");

                    b.Property<string>("refresh_token")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("refresh_token_expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("reset_token")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("reset_token_expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("roles")
                        .HasColumnType("longtext");

                    b.Property<string>("skills")
                        .HasColumnType("longtext");

                    b.Property<string>("social_links")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.Property<string>("wished_job_categories")
                        .HasColumnType("longtext");

                    b.Property<string>("wished_job_locations")
                        .HasColumnType("longtext");

                    b.Property<string>("wished_job_types")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.NotificationSettings", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Users", "user")
                        .WithOne("notification_settings")
                        .HasForeignKey("KiwiTaskAPI.Models.NotificationSettings", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.PreferredCategories", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Users", "user")
                        .WithMany("preferred_categories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskAttachment", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Tasks", null)
                        .WithMany("task_attachments")
                        .HasForeignKey("Tasksid");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskCates", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Tasks", "task")
                        .WithMany("categories")
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("task");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskComments", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("commenter_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiwiTaskAPI.Models.Tasks", "task")
                        .WithMany("comments")
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("task");

                    b.Navigation("user");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskOffers", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Tasks", "task")
                        .WithMany("offers")
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiwiTaskAPI.Models.Users", "user")
                        .WithMany("offers")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("task");

                    b.Navigation("user");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Tasks", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Users", "poster")
                        .WithMany("tasks")
                        .HasForeignKey("poster_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("poster");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.UserPassword", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Users", "user")
                        .WithOne("user_password")
                        .HasForeignKey("KiwiTaskAPI.Models.UserPassword", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Tasks", b =>
                {
                    b.Navigation("categories");

                    b.Navigation("comments");

                    b.Navigation("offers");

                    b.Navigation("task_attachments");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Users", b =>
                {
                    b.Navigation("notification_settings");

                    b.Navigation("offers");

                    b.Navigation("preferred_categories");

                    b.Navigation("tasks");

                    b.Navigation("user_password");
                });
#pragma warning restore 612, 618
        }
    }
}
