// <auto-generated />
using System;
using KiwiTaskAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiwiTaskAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426072315_InitialCreate_01")]
    partial class InitialCreate_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KiwiTaskAPI.Models.Attachment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<Guid?>("Tasksid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ctx_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("uploader_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Tasksid");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskCategory", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("task_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("taskid")
                        .HasColumnType("char(36)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("taskid");

                    b.ToTable("task_categories");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Tasks", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("budget")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("budget_amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("city")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("estimated_hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("postcode")
                        .HasColumnType("longtext");

                    b.Property<Guid>("poster_id")
                        .HasColumnType("char(36)");

                    b.Property<int>("pricing_type")
                        .HasColumnType("int");

                    b.Property<string>("suburb")
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.UserPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("user_password");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Users", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("avatar_url")
                        .HasColumnType("longtext");

                    b.Property<string>("bio")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("educations")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("experiences")
                        .HasColumnType("longtext");

                    b.Property<string>("firstname")
                        .HasColumnType("longtext");

                    b.Property<string>("introduction")
                        .HasColumnType("longtext");

                    b.Property<bool?>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("is_recommand_required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("lastname")
                        .HasColumnType("longtext");

                    b.Property<string>("phone_number")
                        .HasColumnType("longtext");

                    b.Property<string>("refresh_token")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("refresh_token_expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("reset_token")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("reset_token_expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("roles")
                        .HasColumnType("longtext");

                    b.Property<string>("skills")
                        .HasColumnType("longtext");

                    b.Property<string>("social_links")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("user_passwordid")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.Property<string>("wished_job_categories")
                        .HasColumnType("longtext");

                    b.Property<string>("wished_job_locations")
                        .HasColumnType("longtext");

                    b.Property<string>("wished_job_types")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("user_passwordid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Attachment", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Tasks", null)
                        .WithMany("attachments")
                        .HasForeignKey("Tasksid");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.TaskCategory", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.Tasks", "task")
                        .WithMany("TaskCategories")
                        .HasForeignKey("taskid");

                    b.Navigation("task");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Users", b =>
                {
                    b.HasOne("KiwiTaskAPI.Models.UserPassword", "user_password")
                        .WithMany()
                        .HasForeignKey("user_passwordid");

                    b.Navigation("user_password");
                });

            modelBuilder.Entity("KiwiTaskAPI.Models.Tasks", b =>
                {
                    b.Navigation("TaskCategories");

                    b.Navigation("attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
